### ISSUE TITLE
ModuleNotFoundError: No module named 'nomad_dos_fingerprints' when importing madas.fingerprints.DOS_fingerprint

### ISSUE THREAD

**Issue by tisabe** [kubanmar/madas#2]
`nomad_dos_fingerprints` seems to be used in `DOS_fingerprint.py` module, but is not listed in requirements.

**Comment by kubanmar** [comment]
This is related to #1: The old instructions for installing from source did not include recursive cloning (`git clone --recurse-submodules https://github.com/kubanmar/madas.git`), is required to install the `nomad_dos_fingerprints` package. This should be fixed with the newest version of the documentation.
